
# Identity
id: "survisland"
name: "Survisland"
author: "Stoupy51"
version: "2.1.5"
minecraft: "1.21.7"

# Some directories
directory: "."
output: "build"

# A list of importable plugin strings
require:
    - "stewbeet.plugins.initialize"

# Takes a nested pack config, see PackConfig() documentation
data_pack:
    name: "datapack"
    load: ["merge/datapack"]

# Takes a nested pack config, see PackConfig() documentation
resource_pack:
    name: resource_pack
    load: ["merge/resource_pack"]

# A list of strings or dicts representing "plugins".
# - These plugins will execute after the pack is loaded
# - If item = str, should be a path to an importable plugin (ex: "stewbeet.plugins.auto_lang")
# - If item = dict, should be a nestable project config
#     - Each sub-pipeline creates a temp context inheriting the parent context
pipeline:
    - "user.setup_definitions" # User code
    - "stewbeet.plugins.verify_definitions"
    - "stewbeet.plugins.resource_pack.sounds"
    - "stewbeet.plugins.resource_pack.item_models"
    - "stewbeet.plugins.resource_pack.check_power_of_2"
    - "stewbeet.plugins.custom_recipes"
    - "stewbeet.plugins.ingame_manual"
    - "stewbeet.plugins.datapack.loading"
    - "stewbeet.plugins.datapack.custom_blocks"
    - "stewbeet.plugins.datapack.loot_tables"
    - "stewbeet.plugins.compatibilities.simpledrawer"
    - "stewbeet.plugins.compatibilities.neo_enchant"
    - "user.link" # User code
    - "stewbeet.plugins.finalyze.custom_blocks_ticking"
    - "stewbeet.plugins.finalyze.basic_datapack_structure"
    - "stewbeet.plugins.finalyze.dependencies"
    - "stewbeet.plugins.finalyze.check_unused_textures"
    - "stewbeet.plugins.auto.headers"
    - "stewbeet.plugins.archive"
    - "stewbeet.plugins.merge_smithed_weld"
    - "stewbeet.plugins.copy_to_destination"
    - "stewbeet.plugins.compute_sha1"

# Generic dict which holds extra information usable by plugins
meta:
    # Model resolver configuration for caching models
    model_resolver:
        use_cache: true

    # StewBeet specific configuration
    stewbeet:
        # Directory containing all project textures
        textures_folder: "assets/textures"
        # Directory containing all custom sounds
        sounds_folder: "assets/sounds"
        # Directory containing all jukebox records
        records_folder: "assets/records"
        # Directory containing libraries that will be copied to the build destination, and merged using Smithed Weld if enabled.
        libs_folder: "libs"
        # Path where definitions debug information will be dumped
        definitions_debug: "definitions_debug.json"
        # Optional list of destination paths where generated files will be copied
        build_copy_destinations:
            # Paths to copy the datapack(s) to
            datapack: ["D:/latest_snapshot/world/datapacks"]
            # Paths to copy the resource pack(s) to
            resource_pack: ["D:/minecraft/snapshot/resourcepacks"]

        # Configuration for in-game manual
        manual:
            high_resolution: true
            cache_path: "manual_cache"
            cache_assets: true
            cache_pages: false
            json_dump_path: "manual_cache/content.json"
            first_page_text: [{"text":"Ratio gold", "color":"#505050"}]

