[project]
name = "survisland"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "smithed",
    "stewbeet>=3.8.1",
]

[tool.uv.sources]
smithed = { git = "https://github.com/Stoupy51/smithed-python.git" }
#(stewbeet = { git = "https://github.com/Stoupy51/StewBeet.git", subdirectory = "python_package", rev = "main" }

